config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders
  resources :cart_items, only: [:create, :destroy]
  resources :carts
  resources :products do
    collection do
      get 'list', action: :list
    end
  end
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items

  def sub_total
    sum = 0
    cart_items.each do |cart_item|
      sum += (cart_item.quantity * cart_item.product.price)
    end
    sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  # def index
  #   @carts = Cart.all
  # end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = @current_cart
  end

  # GET /carts/new
  # def new
  #   @cart = Cart.new
  # end

  # GET /carts/1/edit
  # def edit
  # end

  # POST /carts
  # POST /carts.json
  # def create
  #   @cart = Cart.new(cart_params)

  #   respond_to do |format|
  #     if @cart.save
  #       format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
  #       format.json { render :show, status: :created, location: @cart }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @cart.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  # def update
  #   respond_to do |format|
  #     if @cart.update(cart_params)
  #       format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @cart }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @cart.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    # @cart.destroy
    # respond_to do |format|
    #   format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  private
    # # Use callbacks to share common setup or constraints between actions.
    # def set_cart
    #   @cart = Cart.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def add_items_to_cart(chosen_product)
      # If cart already has this product then find the relevant cart_item
      # and iterate quantity otherwise create a new cart_item for this product
      if @current_cart.products.include?(chosen_product)
        # Find the cart_item with the chosen_product
        @cart_item = @current_cart.cart_items.find_by(product_id: chosen_product)
        # Iterate the cart_item's quantity by one
        @cart_item.quantity += 1
      else
        @cart_item = CartItem.new
        @cart_item.cart = @current_cart
        @cart_item.product = chosen_product
        # @cart_item.order = Order.first
        @cart_item.quantity = params[:quantity].to_i || 1
      end
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="hero-wrap hero-bread" style="background-image: url('../images/bg_6.jpg');">
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs"><span class="mr-2"><a href="/">Home</a></span> <span>Cart</span></p>
        <h1 class="mb-0 bread">My Cart</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section ftco-cart">
  <div class="container">
    <div class="row">
      <div class="col-md-12 ftco-animate">
        <div class="cart-list">
          <table class="table">
            <thead class="thead-primary">
              <tr class="text-center">
                <th>&nbsp;</th>
                <th>&nbsp;</th>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>

            <% @cart.cart_items.each do |item| %>
              <tr class="text-center">
                <td class="product-remove">
                  <a href="<%= cart_item_path(item) %>" data-method="delete" data-confirm="Are you sure?">
                    <span class="ion-ios-close"></span>
                  </a>
                </td>
                
                <td class="image-prod">
                  <div class="img" style="background-image:url(../<%= item.product.image %>);"></div>
                </td>
                
                <td class="product-name">
                  <h3><%= item.product.name %></h3>
                  <p><%= truncate(item.product.description, length: 100) %></p>
                </td>
                
                <td class="price">$<%= item.product.price %></td>
                
                <td class="quantity">
                  <div class="input-group mb-3">
                    <input type="text" name="quantity" class="quantity form-control input-number" value="<%= item.quantity %>" min="1" max="100">
                  </div>
                </td>
                
                <td class="total">$<%= item.quantity * item.product.price %></td>
              </tr><!-- END TR-->
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <% if @current_cart.cart_items.count > 0 %>
      <div class="row justify-content-center">
        <div class="col col-lg-5 col-md-6 mt-5 cart-wrap ftco-animate">
          <div class="cart-total mb-3">
            <h3>Cart Totals</h3>
            <p class="d-flex">
              <span>Subtotal</span>
              <span>$<%= @cart.sub_total %></span>
            </p>
            <p class="d-flex">
              <span>Delivery</span>
              <span>$0.00</span>
            </p>
            <p class="d-flex">
              <span>Discount</span>
              <span>$0.00</span>
            </p>
            <hr>
            <p class="d-flex total-price">
              <span>Total</span>
              <span>$<%= @cart.sub_total %></span>
            </p>
          </div>
          <p class="text-center"><a href="<%= new_order_path %>" class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
        </div>
      </div>
    <% end %>
  </div>
</section>