config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders
  resources :cart_items, only: [:create, :destroy]
  resources :carts
  resources :products do
    collection do
      get 'list', action: :list
    end
  end
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  # before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  # # GET /cart_items
  # # GET /cart_items.json
  # def index
  #   @cart_items = CartItem.all
  # end

  # # GET /cart_items/1
  # # GET /cart_items/1.json
  # def show
  # end

  # # GET /cart_items/new
  # def new
  #   @cart_item = CartItem.new
  # end

  # # GET /cart_items/1/edit
  # def edit
  # end

  # # POST /cart_items
  # # POST /cart_items.json
  # def create
  #   @cart_item = CartItem.new(cart_item_params)

  #   respond_to do |format|
  #     if @cart_item.save
  #       format.html { redirect_to @cart_item, notice: 'Cart item was successfully created.' }
  #       format.json { render :show, status: :created, location: @cart_item }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @cart_item.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /cart_items/1
  # # PATCH/PUT /cart_items/1.json
  # def update
  #   respond_to do |format|
  #     if @cart_item.update(cart_item_params)
  #       format.html { redirect_to @cart_item, notice: 'Cart item was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @cart_item }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @cart_item.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /cart_items/1
  # # DELETE /cart_items/1.json
  # def destroy
  #   @cart_item.destroy
  #   respond_to do |format|
  #     format.html { redirect_to cart_items_url, notice: 'Cart item was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  # private
  #   # Use callbacks to share common setup or constraints between actions.
  #   def set_cart_item
  #     @cart_item = CartItem.find(params[:id])
  #   end

  #   # Never trust parameters from the scary internet, only allow the white list through.
  #   def cart_item_params
  #     params.require(:cart_item).permit(:product_id, :cart_id, :quantity)
  #   end
  # skip_before_action :verify_authenticity_token
  def create
    # Find associated product and current cart
    chosen_product = Product.find(params[:product_id])
    add_items_to_cart(chosen_product)
    respond_to do |format|
      if @cart_item.save!
        if params[:add_to_cart].present?
          
        end
        format.html { redirect_back(fallback_location: @current_cart) }
        format.js
      else
        format.html { render :new, notice: 'Error adding product to basket!' }
      end
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_back(fallback_location: @current_cart)
  end

  # def add_quantity
  #   @cart_item = CartItem.find(params[:id])
  #   @cart_item.quantity += 1
  #   @cart_item.save
  #   redirect_back(fallback_location: @current_cart)
  # end

  # def reduce_quantity
  #   @cart_item = CartItem.find(params[:id])
  #   if @cart_item.quantity > 1
  #     @cart_item.quantity -= 1
  #     @cart_item.save
  #     redirect_back(fallback_location: @current_cart)
  #   elsif @cart_item.quantity == 1
  #     destroy
  #   end
  # end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity, :product_id, :cart_id)
  end

  def add_items_to_cart(chosen_product)
    # If cart already has this product then find the relevant cart_item
    # and iterate quantity otherwise create a new cart_item for this product
    if @current_cart.products.include?(chosen_product)
      # Find the cart_item with the chosen_product
      @cart_item = @current_cart.cart_items.find_by(product_id: chosen_product)
      # Iterate the cart_item's quantity by one
      @cart_item.quantity += 1
    else
      @cart_item = CartItem.new
      @cart_item.cart = @current_cart
      @cart_item.product = chosen_product
      # @cart_item.order = Order.first
      @cart_item.quantity = params[:quantity].to_i || 1
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_form.html.erb
<%= form_with(model: cart_item, local: true) do |form| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_items/create.js.erb
$('#total_cart_items_badge').html("(<%= @current_cart.cart_items.count %>)");

app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cart Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.product %></td>
        <td><%= cart_item.cart %></td>
        <td><%= cart_item.quantity %></td>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart Item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @cart_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @cart_item.cart %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart_item.quantity %>
</p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>