config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders
  resources :cart_items, only: [:create, :destroy]
  resources :carts
  resources :products do
    collection do
      get 'list', action: :list
    end
  end
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def list
    @products = Product.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :description, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="hero-wrap hero-bread" style="background-image: url('../../images/bg_6.jpg');">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Product</span></p>
            <h1 class="mb-0 bread">Product</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-8 ftco-animate">
            <%= form_with(model: product, local: true) do |form| %>
							<h3 class="mb-4 billing-heading">Product Info</h3>
              <div class="row align-items-end">
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="name">Product Name</label>
                    <%= form.text_field :image, class: "form-control", placeholder: "" %>
                  </div>
                </div>
                <div class="w-100"></div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="image">Product Image</label>
                    <%= form.text_field :image, class: "form-control", placeholder: "" %>
                  </div>
                </div>
                <div class="w-100"></div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="description">Description</label>
                    <%= form.text_area :description, class: 'form-control', rows: "5", placeholder: "" %>
                  </div>
                </div>
                <div class="w-100"></div>
                <div class="col-md-12">
                  <div class="form-group">
                    <label for="price">Price</label>
                    <%= form.text_field :price, class: "form-control", placeholder: "" %>
                  </div>
                </div>
                <div class="col-md-12">
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary py-3 px-4">Save</button>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>

app/views/products/_product_item.html.erb
<div class="col-sm-6 col-md-6 col-lg-4 ftco-animate">
  <div class="product">
    <a href="<%= product_path(product) %>" class="img-prod"><img class="img-fluid" src="<%= product.image %>" alt="Colorlib Template">
      <div class="overlay"></div>
    </a>
    <div class="text py-3 px-3">
      <h3><a href="#"><%= product.name %></a></h3>
      <div class="d-flex">
        <div class="pricing">
          <p class="price"><span>$<%= product.price %></span></p>
        </div>
        <div class="rating">
          <p class="text-right">
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
          </p>
        </div>
      </div>
      <form action="/cart_items" id="item-form-<%= product.id %>" class="item-form" method="POST">
        <input type="hidden" name="product_id" value="<%= product.id %>">
        <input type="hidden" name="quantity" value="1">
        <p class="bottom-area d-flex px-3">
          <a href="javascript:{}" onclick="document.getElementById('item-form-<%= product.id %>').submit();" class="add-to-cart text-center py-2 mr-1"><span>Add to cart <i class="ion-ios-add ml-1"></i></span></a>
          <a href="#" class="buy-now text-center py-2">Buy now<span><i class="ion-ios-cart ml-1"></i></span></a>
        </p>
      </form>
    </div>
  </div>
</div>

app/views/products/_product_item_mgm.html.erb
<div class="col-sm-6 col-md-6 col-lg-4 ftco-animate">
  <div class="product">
    <a href="<%= product_path(product) %>" class="img-prod"><img class="img-fluid" src="../<%= product.image %>" alt="Colorlib Template">
      <div class="overlay"></div>
    </a>
    <div class="text py-3 px-3">
      <h3><a href="<%= product_path(product) %>"><%= product.name %></a></h3>
      <div class="d-flex">
        <div class="pricing">
          <p class="price"><span>$<%= product.price %></span></p>
        </div>
        <div class="rating">
          <p class="text-right">
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
          </p>
        </div>
      </div>
      <p class="bottom-area d-flex px-3">
        <a href="<%= edit_product_path(product) %>" class="buy-now text-center py-2">Edit</a>
        <a href="<%= product_path(product) %>" class="buy-now text-center py-2" data-method="delete" data-confirm="Are you sure?">Delete</a>
      </p>
    </div>
  </div>
</div>

app/views/products/_sidebar.html.erb
<div class="col-md-4 col-lg-2 sidebar">
  <div class="sidebar-box-2">
    <h2 class="heading mb-4"><a href="#">Clothing</a></h2>
    <ul>
      <li><a href="#">Shirts &amp; Tops</a></li>
      <li><a href="#">Dresses</a></li>
      <li><a href="#">Shorts &amp; Skirts</a></li>
      <li><a href="#">Jackets</a></li>
      <li><a href="#">Coats</a></li>
      <li><a href="#">Sleeveless</a></li>
      <li><a href="#">Trousers</a></li>
      <li><a href="#">Winter Coats</a></li>
      <li><a href="#">Jumpsuits</a></li>
    </ul>
  </div>
  <div class="sidebar-box-2">
    <h2 class="heading mb-4"><a href="#">Jeans</a></h2>
    <ul>
      <li><a href="#">Shirts &amp; Tops</a></li>
      <li><a href="#">Dresses</a></li>
      <li><a href="#">Shorts &amp; Skirts</a></li>
      <li><a href="#">Jackets</a></li>
      <li><a href="#">Coats</a></li>
      <li><a href="#">Jeans</a></li>
      <li><a href="#">Sleeveless</a></li>
      <li><a href="#">Trousers</a></li>
      <li><a href="#">Winter Coats</a></li>
      <li><a href="#">Jumpsuits</a></li>
    </ul>
  </div>
  <div class="sidebar-box-2">
    <h2 class="heading mb-2"><a href="#">Bags</a></h2>
    <h2 class="heading mb-2"><a href="#">Accessories</a></h2>
  </div>
  <div class="sidebar-box-2">
    <h2 class="heading mb-4"><a href="#">Shoes</a></h2>
    <ul>
      <li><a href="#">Nike</a></li>
      <li><a href="#">Addidas</a></li>
      <li><a href="#">Skechers</a></li>
      <li><a href="#">Jackets</a></li>
      <li><a href="#">Coats</a></li>
      <li><a href="#">Jeans</a></li>
    </ul>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<div class="hero-wrap hero-bread" style="background-image: url('images/bg_6.jpg');">
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs"><span class="mr-2"><a href="/">Home</a></span> <span>Products</span></p>
        <h1 class="mb-0 bread">Collection Products</h1>
      </div>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>
<section class="ftco-section bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-10 order-md-last">
        <div class="row">
          <% @products.each do |product| %>
            <%= render partial: 'product_item', locals: { product: product } %>
          <% end %>
        </div>
      </div>
      <%= render partial: 'sidebar' %>
    </div>
  </div>
</section>

app/views/products/list.html.erb
<div class="hero-wrap hero-bread" style="background-image: url('../images/bg_6.jpg');">
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs"><span class="mr-2"><a href="/">Home</a></span> <span>Products</span></p>
        <h1 class="mb-0 bread">Collection Products</h1>
      </div>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>
<section class="ftco-section bg-light">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-lg-10 order-md-last">
        <div class="row">
          <% @products.each do |product| %>
            <%= render partial: 'product_item_mgm', locals: { product: product } %>
          <% end %>
        </div>
      </div>
      <%= render partial: 'sidebar' %>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<div class="hero-wrap hero-bread" style="background-image: url('../images/bg_6.jpg');">
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs"><span class="mr-2"><a href="/">Home</a></span> <span class="mr-2"><a href="<%= product_path %>">Product</a></span> <span>Product Detail</span></p>
        <h1 class="mb-0 bread">Product Detail</h1>
      </div>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>
<section class="ftco-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 mb-5 ftco-animate">
        <a href="../../images/menu-2.jpg" class="image-popup"><img src="../<%= @product.image %>" class="img-fluid" alt="Colorlib Template"></a>
      </div>
      <div class="col-lg-6 product-details pl-md-5 ftco-animate">
        <h3><%= @product.name %></h3>
        <div class="rating d-flex">
          <p class="text-left mr-4">
            <a href="#" class="mr-2">5.0</a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
            <a href="#"><span class="ion-ios-star-outline"></span></a>
          </p>
          <p class="text-left mr-4">
            <a href="#" class="mr-2" style="color: #000;">100 <span style="color: #bbb;">Rating</span></a>
          </p>
          <p class="text-left">
            <a href="#" class="mr-2" style="color: #000;">500 <span style="color: #bbb;">Sold</span></a>
          </p>
        </div>
        <p class="price"><span>$<%= @product.price %></span></p>
        <p><%= @product.description %>
        </p>
        <div class="row mt-4">
          <div class="col-md-6">
            <div class="form-group d-flex">
              <div class="select-wrap">
                <div class="icon"><span class="ion-ios-arrow-down"></span></div>
                <select name="" id="" class="form-control">
                  <option value="">Small</option>
                  <option value="">Medium</option>
                  <option value="">Large</option>
                  <option value="">Extra Large</option>
                </select>
              </div>
            </div>
          </div>
          <div class="w-100"></div>
          <form action="/cart_items" id="cart-item-form" class="cart-item-form" method="POST">
          <div class="input-group col-md-8 d-flex mb-3">
            <span class="input-group-btn mr-2">
                <button type="button" class="quantity-left-minus btn"  data-type="minus" data-field="">
                  <i class="ion-ios-remove"></i>
                </button>
              </span>
            <input type="text" id="quantity" name="quantity" class="form-control input-number" value="1" min="1" max="100">
            <input type="hidden" name="product_id" value="<%= @product.id %>">
            <span class="input-group-btn ml-2">
                <button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">
                    <i class="ion-ios-add"></i>
                </button>
            </span>
          </div>
          <div class="w-100"></div>
          <div class="col-md-12">
            <p style="color: #000;">80 piece available</p>
          </div>
        </div>
        <p><a href="javascript:{}" onclick="document.getElementById('cart-item-form').submit();" class="btn btn-black py-3 px-5">Add to Cart</a></p>
        </form>
      </div>
    </div>
  </div>
</section>